# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CronosWidget.ui'
#
# Created: Thu Jul 11 20:35:23 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(641, 756)
        self.butt_Exit = QtGui.QPushButton(Form)
        self.butt_Exit.setGeometry(QtCore.QRect(30, 690, 98, 27))
        self.butt_Exit.setObjectName(_fromUtf8("butt_Exit"))
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 28, 261, 221))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.list_projs = QtGui.QListWidget(self.layoutWidget)
        self.list_projs.setObjectName(_fromUtf8("list_projs"))
        self.verticalLayout.addWidget(self.list_projs)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.butt_ScanFolder = QtGui.QPushButton(self.layoutWidget)
        self.butt_ScanFolder.setObjectName(_fromUtf8("butt_ScanFolder"))
        self.horizontalLayout.addWidget(self.butt_ScanFolder)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.butt_ScanFrames = QtGui.QPushButton(self.layoutWidget)
        self.butt_ScanFrames.setObjectName(_fromUtf8("butt_ScanFrames"))
        self.horizontalLayout.addWidget(self.butt_ScanFrames)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.info_list = QtGui.QListWidget(Form)
        self.info_list.setGeometry(QtCore.QRect(40, 490, 256, 192))
        self.info_list.setObjectName(_fromUtf8("info_list"))
        self.layoutWidget1 = QtGui.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(41, 260, 261, 89))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_frames = QtGui.QLabel(self.layoutWidget1)
        self.label_frames.setObjectName(_fromUtf8("label_frames"))
        self.verticalLayout_3.addWidget(self.label_frames)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.slider_timestep = QtGui.QSlider(self.layoutWidget1)
        self.slider_timestep.setOrientation(QtCore.Qt.Horizontal)
        self.slider_timestep.setObjectName(_fromUtf8("slider_timestep"))
        self.horizontalLayout_2.addWidget(self.slider_timestep)
        self.spinBox_timestep = QtGui.QSpinBox(self.layoutWidget1)
        self.spinBox_timestep.setObjectName(_fromUtf8("spinBox_timestep"))
        self.horizontalLayout_2.addWidget(self.spinBox_timestep)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.info_timestep = QtGui.QLineEdit(self.layoutWidget1)
        self.info_timestep.setObjectName(_fromUtf8("info_timestep"))
        self.verticalLayout_3.addWidget(self.info_timestep)
        self.layoutWidget2 = QtGui.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(42, 370, 261, 29))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_fieldChoice = QtGui.QLabel(self.layoutWidget2)
        self.label_fieldChoice.setObjectName(_fromUtf8("label_fieldChoice"))
        self.horizontalLayout_3.addWidget(self.label_fieldChoice)
        self.select_fields = QtGui.QComboBox(self.layoutWidget2)
        self.select_fields.setObjectName(_fromUtf8("select_fields"))
        self.horizontalLayout_3.addWidget(self.select_fields)
        self.layoutWidget3 = QtGui.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(41, 410, 261, 29))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_mod = QtGui.QLabel(self.layoutWidget3)
        self.label_mod.setObjectName(_fromUtf8("label_mod"))
        self.horizontalLayout_4.addWidget(self.label_mod)
        self.select_mod = QtGui.QComboBox(self.layoutWidget3)
        self.select_mod.setObjectName(_fromUtf8("select_mod"))
        self.horizontalLayout_4.addWidget(self.select_mod)
        self.layoutWidget4 = QtGui.QWidget(Form)
        self.layoutWidget4.setGeometry(QtCore.QRect(40, 450, 261, 24))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_scaling = QtGui.QLabel(self.layoutWidget4)
        self.label_scaling.setObjectName(_fromUtf8("label_scaling"))
        self.horizontalLayout_5.addWidget(self.label_scaling)
        self.butt_linear = QtGui.QRadioButton(self.layoutWidget4)
        self.butt_linear.setObjectName(_fromUtf8("butt_linear"))
        self.horizontalLayout_5.addWidget(self.butt_linear)
        self.butt_log = QtGui.QRadioButton(self.layoutWidget4)
        self.butt_log.setObjectName(_fromUtf8("butt_log"))
        self.horizontalLayout_5.addWidget(self.butt_log)
        self.list_dataProperties = QtGui.QListWidget(Form)
        self.list_dataProperties.setGeometry(QtCore.QRect(350, 470, 251, 161))
        self.list_dataProperties.setObjectName(_fromUtf8("list_dataProperties"))
        self.layoutWidget5 = QtGui.QWidget(Form)
        self.layoutWidget5.setGeometry(QtCore.QRect(510, 650, 91, 52))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.layoutWidget5)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.select_OutputFormat = QtGui.QComboBox(self.layoutWidget5)
        self.select_OutputFormat.setObjectName(_fromUtf8("select_OutputFormat"))
        self.verticalLayout_5.addWidget(self.select_OutputFormat)
        self.Contour = QtGui.QTabWidget(Form)
        self.Contour.setGeometry(QtCore.QRect(320, 30, 301, 411))
        self.Contour.setObjectName(_fromUtf8("Contour"))
        self.Contour1 = QtGui.QWidget()
        self.Contour1.setObjectName(_fromUtf8("Contour1"))
        self.layoutWidget6 = QtGui.QWidget(self.Contour1)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 10, 253, 24))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_slice = QtGui.QLabel(self.layoutWidget6)
        self.label_slice.setObjectName(_fromUtf8("label_slice"))
        self.horizontalLayout_6.addWidget(self.label_slice)
        self.butt_plane_xy = QtGui.QRadioButton(self.layoutWidget6)
        self.butt_plane_xy.setObjectName(_fromUtf8("butt_plane_xy"))
        self.horizontalLayout_6.addWidget(self.butt_plane_xy)
        self.butt_plane_xz = QtGui.QRadioButton(self.layoutWidget6)
        self.butt_plane_xz.setObjectName(_fromUtf8("butt_plane_xz"))
        self.horizontalLayout_6.addWidget(self.butt_plane_xz)
        self.butt_plane_yz = QtGui.QRadioButton(self.layoutWidget6)
        self.butt_plane_yz.setObjectName(_fromUtf8("butt_plane_yz"))
        self.horizontalLayout_6.addWidget(self.butt_plane_yz)
        self.layoutWidget7 = QtGui.QWidget(self.Contour1)
        self.layoutWidget7.setGeometry(QtCore.QRect(20, 50, 251, 66))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_slice_2 = QtGui.QLabel(self.layoutWidget7)
        self.label_slice_2.setObjectName(_fromUtf8("label_slice_2"))
        self.horizontalLayout_7.addWidget(self.label_slice_2)
        self.slider_slice = QtGui.QSlider(self.layoutWidget7)
        self.slider_slice.setOrientation(QtCore.Qt.Horizontal)
        self.slider_slice.setObjectName(_fromUtf8("slider_slice"))
        self.horizontalLayout_7.addWidget(self.slider_slice)
        self.spinBox_slice = QtGui.QSpinBox(self.layoutWidget7)
        self.spinBox_slice.setObjectName(_fromUtf8("spinBox_slice"))
        self.horizontalLayout_7.addWidget(self.spinBox_slice)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.info_slice = QtGui.QLineEdit(self.layoutWidget7)
        self.info_slice.setObjectName(_fromUtf8("info_slice"))
        self.verticalLayout_2.addWidget(self.info_slice)
        self.layoutWidget8 = QtGui.QWidget(self.Contour1)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 310, 181, 52))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtGui.QLabel(self.layoutWidget8)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.splitter = QtGui.QSplitter(self.layoutWidget8)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.lineEdit_colorTable = QtGui.QLineEdit(self.splitter)
        self.lineEdit_colorTable.setObjectName(_fromUtf8("lineEdit_colorTable"))
        self.spinBox_colorTable = QtGui.QSpinBox(self.splitter)
        self.spinBox_colorTable.setObjectName(_fromUtf8("spinBox_colorTable"))
        self.verticalLayout_4.addWidget(self.splitter)
        self.label_3 = QtGui.QLabel(self.Contour1)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 121, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.layoutWidget9 = QtGui.QWidget(self.Contour1)
        self.layoutWidget9.setGeometry(QtCore.QRect(20, 250, 271, 24))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.butt_showCells = QtGui.QRadioButton(self.layoutWidget9)
        self.butt_showCells.setObjectName(_fromUtf8("butt_showCells"))
        self.horizontalLayout_8.addWidget(self.butt_showCells)
        self.butt_showSmooth = QtGui.QRadioButton(self.layoutWidget9)
        self.butt_showSmooth.setObjectName(_fromUtf8("butt_showSmooth"))
        self.horizontalLayout_8.addWidget(self.butt_showSmooth)
        self.butt_plotContour = QtGui.QPushButton(self.Contour1)
        self.butt_plotContour.setGeometry(QtCore.QRect(200, 340, 98, 27))
        self.butt_plotContour.setObjectName(_fromUtf8("butt_plotContour"))
        self.layoutWidget10 = QtGui.QWidget(self.Contour1)
        self.layoutWidget10.setGeometry(QtCore.QRect(190, 130, 102, 80))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.butt_CoordCart = QtGui.QRadioButton(self.layoutWidget10)
        self.butt_CoordCart.setObjectName(_fromUtf8("butt_CoordCart"))
        self.verticalLayout_6.addWidget(self.butt_CoordCart)
        self.butt_CoordCyl = QtGui.QRadioButton(self.layoutWidget10)
        self.butt_CoordCyl.setObjectName(_fromUtf8("butt_CoordCyl"))
        self.verticalLayout_6.addWidget(self.butt_CoordCyl)
        self.butt_CoordSph = QtGui.QRadioButton(self.layoutWidget10)
        self.butt_CoordSph.setObjectName(_fromUtf8("butt_CoordSph"))
        self.verticalLayout_6.addWidget(self.butt_CoordSph)
        self.label_4 = QtGui.QLabel(self.Contour1)
        self.label_4.setGeometry(QtCore.QRect(70, 130, 111, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.butt_contLines = QtGui.QRadioButton(self.Contour1)
        self.butt_contLines.setGeometry(QtCore.QRect(20, 280, 191, 22))
        self.butt_contLines.setObjectName(_fromUtf8("butt_contLines"))
        self.Contour.addTab(self.Contour1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget11 = QtGui.QWidget(self.tab_2)
        self.layoutWidget11.setGeometry(QtCore.QRect(30, 20, 203, 24))
        self.layoutWidget11.setObjectName(_fromUtf8("layoutWidget11"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget11)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_5 = QtGui.QLabel(self.layoutWidget11)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_9.addWidget(self.label_5)
        self.butt_Dir1D_x = QtGui.QRadioButton(self.layoutWidget11)
        self.butt_Dir1D_x.setObjectName(_fromUtf8("butt_Dir1D_x"))
        self.horizontalLayout_9.addWidget(self.butt_Dir1D_x)
        self.butt_Dir1D_y = QtGui.QRadioButton(self.layoutWidget11)
        self.butt_Dir1D_y.setObjectName(_fromUtf8("butt_Dir1D_y"))
        self.horizontalLayout_9.addWidget(self.butt_Dir1D_y)
        self.butt_Dir1D_z = QtGui.QRadioButton(self.layoutWidget11)
        self.butt_Dir1D_z.setObjectName(_fromUtf8("butt_Dir1D_z"))
        self.horizontalLayout_9.addWidget(self.butt_Dir1D_z)
        self.butt_LinePlot = QtGui.QPushButton(self.tab_2)
        self.butt_LinePlot.setGeometry(QtCore.QRect(180, 320, 98, 27))
        self.butt_LinePlot.setObjectName(_fromUtf8("butt_LinePlot"))
        self.widget = QtGui.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(10, 50, 271, 120))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_slice1D_1 = QtGui.QLabel(self.widget)
        self.label_slice1D_1.setObjectName(_fromUtf8("label_slice1D_1"))
        self.verticalLayout_7.addWidget(self.label_slice1D_1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.slider_slice1DPerp1 = QtGui.QSlider(self.widget)
        self.slider_slice1DPerp1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_slice1DPerp1.setObjectName(_fromUtf8("slider_slice1DPerp1"))
        self.horizontalLayout_10.addWidget(self.slider_slice1DPerp1)
        self.spinBox_slice1DPerp1 = QtGui.QSpinBox(self.widget)
        self.spinBox_slice1DPerp1.setObjectName(_fromUtf8("spinBox_slice1DPerp1"))
        self.horizontalLayout_10.addWidget(self.spinBox_slice1DPerp1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_slice1D_2 = QtGui.QLabel(self.widget)
        self.label_slice1D_2.setObjectName(_fromUtf8("label_slice1D_2"))
        self.verticalLayout_8.addWidget(self.label_slice1D_2)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.slider_slice1DPerp2 = QtGui.QSlider(self.widget)
        self.slider_slice1DPerp2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_slice1DPerp2.setObjectName(_fromUtf8("slider_slice1DPerp2"))
        self.horizontalLayout_11.addWidget(self.slider_slice1DPerp2)
        self.spinBox_slice1DPerp2 = QtGui.QSpinBox(self.widget)
        self.spinBox_slice1DPerp2.setObjectName(_fromUtf8("spinBox_slice1DPerp2"))
        self.horizontalLayout_11.addWidget(self.spinBox_slice1DPerp2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.Contour.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(Form)
        self.Contour.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_Exit.setText(QtGui.QApplication.translate("Form", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_ScanFolder.setText(QtGui.QApplication.translate("Form", "Re-Scan Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_ScanFrames.setText(QtGui.QApplication.translate("Form", "Scan Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.label_frames.setText(QtGui.QApplication.translate("Form", "Choose Timestep", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fieldChoice.setText(QtGui.QApplication.translate("Form", "Fields:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mod.setText(QtGui.QApplication.translate("Form", "Modifiers:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_scaling.setText(QtGui.QApplication.translate("Form", "Scaling:", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_linear.setText(QtGui.QApplication.translate("Form", "linear", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_log.setText(QtGui.QApplication.translate("Form", "log", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Output to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_slice.setText(QtGui.QApplication.translate("Form", "Show plane:", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_plane_xy.setText(QtGui.QApplication.translate("Form", "x-y", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_plane_xz.setText(QtGui.QApplication.translate("Form", "x-z", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_plane_yz.setText(QtGui.QApplication.translate("Form", "y-z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_slice_2.setText(QtGui.QApplication.translate("Form", "Slice at:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Choose color table", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Contour plotting:", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_showCells.setText(QtGui.QApplication.translate("Form", "cell values", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_showSmooth.setText(QtGui.QApplication.translate("Form", "smooth contours", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_plotContour.setText(QtGui.QApplication.translate("Form", "Plot Contour", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_CoordCart.setText(QtGui.QApplication.translate("Form", "Cartesian", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_CoordCyl.setText(QtGui.QApplication.translate("Form", "Cylindrical", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_CoordSph.setText(QtGui.QApplication.translate("Form", "Spherical", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Coordinate type:", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_contLines.setText(QtGui.QApplication.translate("Form", "show extra contour lines", None, QtGui.QApplication.UnicodeUTF8))
        self.Contour.setTabText(self.Contour.indexOf(self.Contour1), QtGui.QApplication.translate("Form", "Contour Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Direction:", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_Dir1D_x.setText(QtGui.QApplication.translate("Form", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_Dir1D_y.setText(QtGui.QApplication.translate("Form", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_Dir1D_z.setText(QtGui.QApplication.translate("Form", "z", None, QtGui.QApplication.UnicodeUTF8))
        self.butt_LinePlot.setText(QtGui.QApplication.translate("Form", "Line Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_slice1D_1.setText(QtGui.QApplication.translate("Form", "y =", None, QtGui.QApplication.UnicodeUTF8))
        self.label_slice1D_2.setText(QtGui.QApplication.translate("Form", "z=", None, QtGui.QApplication.UnicodeUTF8))
        self.Contour.setTabText(self.Contour.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Line Plot", None, QtGui.QApplication.UnicodeUTF8))

